### ISSUE TITLE
Folder Name correction in UV_Font

### ISSUE THREAD

**Issue by satya9500** [YuvrajSingh-16/Text-To-Handwritten-Notes#2]
Digits/ and Upper/ folder names in UV_Fonts directory should be in lower case(digits/ and upper/) or will throw an error while running py file choosing UV_Fonts.

**Comment by YuvrajSingh-16** [comment]
Thanks for pointing it out and thanks for reading jt, but it's working with correction too but i am updating it to lower case 😄👍
